	include('MoveGear.lua')
	include('organizer-lib')

send_command('input //lua load porterpacker')
send_command('alias getslips send Lildel "\/\/ exec getslip.txt"')
send_command('alias putslips send Lildel "\/\/ exec putslip.txt"')
send_command('alias getnintools send Lildel "\/\/ exec getnintools.txt')
send_command('alias putnintools send Lildel "\/\/ exec putnintools.txt')
send_command('alias fisherman send Lildel "\/\/ exec Crafting/fisherman.txt"')
send_command('alias tite send Lildel "\/\/ exec tite.txt"; wait 1; send Lildel "\/\/ exec tite.txt"')
send_command('bind  input /item "Smouldering lamp" <stnpc>')
send_command('alias cc input /target <stal>; con sta go Picogelgallo cure')
send_command('alias cme input //send Picodelgallo /ma "Cure VI" <p1>')
send_command('bind ^numpad1 //send Picodelgallo /ma "Curaga III" <p1>')
send_command('alias pstona //send Picodelgallo /ma "Stona" <p1>')
send_command('alias ppara //send Picodelgallo /ma "Paralyna" <p1>')
send_command('alias warp /equip "Left Ring" "Warp Ring"; /wait 8; /item "Warp Ring" <me>')
send_command('alias allwarp //send @all /equip "Left Ring" "Warp Ring"; /wait 8; /item "Warp Ring" <me>')
windower.send_command('bind !w input /equip ring2 "Warp Ring"; /echo Warping; wait 11; input /item "Warp Ring" <me>;')
windower.send_command('bind !q input /equip ring2 "Dim. Ring (Holla)"; /echo Reisenjima; wait 11; input /item "Dim. Ring (Holla)" <me>;')

send_command('alias putmeds send Lildel "\/\/ exec Meds/medstocase.txt')
send_command('alias getmeds send Lildel "\/\/ exec Meds/getmeds.txt')

send_command('alias all //send @all')


send_command('alias packmnk input //po pack export_Lildel_mnk')
send_command('alias packrdm input //po pack export_lildel_rdm')
send_command('alias packnin input //po pack export_lildel_nin')
send_command('alias packblu input //po pack export_lildel_blu')
send_command('alias packcor input //po pack export_lildel_cor')
send_command('alias packdrg input //po pack export_lildel_drg')
send_command('alias packgeo input //po pack export_lildel_geo')
send_command('alias packblu input //po pack export_lildel_blu')
send_command('alias packpld input //po pack export_lildel_pld')
send_command('alias packrun input //po pack export_lildel_run')
send_command('alias packsam input //po pack export_lildel_sam')
send_command('alias packsmn input //po pack export_lildel_smn')
send_command('alias packthf input //po pack export_lildel_thf')
send_command('alias packdnc input //po pack export_lildel_dnc')
send_command('alias packbrd input //po pack export_lildel_brd')
send_command('alias packbst input //po pack export_lildel_bst')
send_command('alias packproc input //po pack export_lildel_proc')
send_command('alias packpup input //po pack export_lildel_pup')
send_command('alias packwhm input //po pack export_lildel_whm')

send_command('alias unpackmnk input //po unpack export_Lildel_mnk')
send_command('alias unpackrdm input //po unpack export_lildel_rdm')
send_command('alias unpacknin input //po unpack export_lildel_nin')
send_command('alias unpackblu input //po unpack export_lildel_blu')
send_command('alias unpackcor input //po unpack export_lildel_cor')
send_command('alias unpackdrg input //po unpack export_lildel_drg')
send_command('alias unpackgeo input //po unpack export_lildel_geo')
send_command('alias unpackblu input //po unpack export_lildel_blu')
send_command('alias unpackpld input //po unpack export_lildel_pld')
send_command('alias unpackrun input //po unpack export_lildel_run')
send_command('alias unpacksam input //po unpack export_lildel_sam')
send_command('alias unpacksmn input //po unpack export_lildel_smn')
send_command('alias unpackthf input //po unpack export_lildel_thf')
send_command('alias unpackdnc input //po unpack export_lildel_dnc')
send_command('alias unpackbrd input //po unpack export_lildel_brd')
send_command('alias unpackbst input //po unpack export_lildel_bst')
send_command('alias unpackproc input //po unpack export_lildel_proc')
send_command('alias unpackpup input //po unpack export_lildel_pup')
send_command('alias unpackwhm input //po unpack export_lildel_whm')

send_command('bind f12 input //ffxidb m z -15')

send_command('bind %f send @others input //hb follow Lildel')
send_command('bind !f send @others input //hb follow off')
send_command('alias macro /item "Macrocosmic Orb" <stnpc>')

    send_command('bind %numpad1 input //fillmode 1')
	send_command('bind %numpad2 input //fillmode 0')
	send_command('alias return input //sw po all return')
	send_command('alias assault input //sw po all assault')
	send_command('alias bolters input //send Picodelgallo /ja "Bolter\'s Roll" <me>')

--Teleport Binds and alias'
send_command('alias aqufim //send @all //hp qufim')
send_command('alias amis //send @all //hp misareaux Coast')
send_command('alias ruah //send Lildel //hp Ru\'Lude Gardens ah')
send_command('bind %m //send Lildel /mount "Byakko"')
send_command('bind ^m //send Picodelgallo /mount "Red Crab"')

send_command('alias ww4 //send Lildel //hp Windurst Waters 4')
send_command('alias ea2 //send Lildel //hp Eastern Adoulin 2')
send_command('alias todo //send Lildel "\/\/ exec todo.txt"')
send_command('alias cure //send Picodelgallo /ma "Cure" <Lildel>')


--pico healing binds

send_command('bind ^o send Picodelgallo //hb on')
send_command('bind !o send Picodelgallo //hb off')


send_command('bind ^f1 send Picodelgallo //ma "Cure IV" <p1>')
send_command('bind ^f2 send Picodelgallo //ma "Cure IV" <p2>')
send_command('bind ^f3 send Picodelgallo //ma "Cure IV" <p3>')
send_command('bind ^f4 send Picodelgallo //ma "Cure IV" <p4>')
send_command('bind ^f5 send Picodelgallo //ma "Cure IV" <p5>')

send_command('bind !f1 send Picoelgallo //ma "Curaga IV" <p1>')
send_command('bind !f2 send Picoelgallo //ma "Curaga IV" <p2>')
send_command('bind !f3 send Picoelgallo //ma "Curaga IV" <p3>')
send_command('bind !f4 send Picoelgallo //ma "Curaga IV" <p4>')
send_command('bind !f5 send Picoelgallo //ma "Curaga IV" <p5>')